name: first-pipeline
on: push
jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: test
        run: echo "this has been triggered ${{ GITHUB_EVENT_NAME }} event "
      - name: build docker image
        run: |
          docker build . 
