name: first-pipeline
on: push
jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Print github workspace
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
      - name: build docker image
        run: |
          docker build . 
