name: first-pipeline
on: push
jobs:
  build-code:
    runs-on: ubuntu-latest
    permissions: 
      read-all|write-all
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build docker image
        run: |
          docker build    
