name: first-pipeline
on: push
jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Print github workspace
        run: |
          echo "GITHUB_SHA = $GITHUB_SHA"
          echo "github.sha = ${{github.sha}}"  
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "github.workspace = ${{ github.workspace }}"
          echo "pr.ref = ${{github.event.pull_request.head.ref}}"
          echo "github.ref = ${{ github.ref }}"
          echo "$GITHUB_CONTEXT"
      - name: Install Maven
        run: sudo apt install maven
      - name: Build application
        run: mvn clean package
      - name: build docker image
        run: |
          docker build -t my-image:latest .
      - name: run docker container
        run: |
          docker run -d --name pipeline -it --rm -p 8888:8080 my-image:latest
